# Generated by Django 2.2.7 on 2019-11-11 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_boast', models.BooleanField()),
                ('post_content', models.CharField(max_length=100)),
                ('up_votes', models.TextField()),
                ('submission_time', models.DateTimeField()),
            ],
        ),
    ]
