# Generated by Django 2.2.7 on 2019-11-11 15:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Ghosts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='boasts_roasts',
            name='down_votes',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='boasts_roasts',
            name='post_content',
            field=models.CharField(max_length=280),
        ),
        migrations.AlterField(
            model_name='boasts_roasts',
            name='submission_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='boasts_roasts',
            name='up_votes',
            field=models.IntegerField(default=0),
        ),
    ]
